/**
 * Cinématique Prompt Builder
 *
 * Implements the 10-layer Cinématique prompt formula from Chapter 6 of the
 * Cinématique Physics and Wardrobe Bible. Transforms a Director's Package
 * (generated by the Expert Council) into a video-generation-ready prompt
 * that satisfies all presence thresholds from Chapter 28.
 *
 * The 10 layers (in order):
 *   1. Environment — space type, era, architecture
 *   2. Time / era — temporal and historical context
 *   3. Subject — position, posture, wardrobe
 *   4. Light source geometry — angle, hardness, direction
 *   5. Light hierarchy — brightest, second, darkest
 *   6. Atmospheric density — haze, smoke, moisture level
 *   7. Foreground depth elements — parallax and occlusion layers
 *   8. Lens and camera position — focal length, height, movement
 *   9. Texture and material cues — surface behavior, fabric, architecture
 *  10. Contrast and color palette — temperature, ratio, saturation
 *
 * Presence threshold overrides (Chapter 28 / Chapter 31):
 *   - Shadow coverage: minimum 70% of frame in deep shadow
 *   - Chiaroscuro ratio: minimum 8:1
 *   - Four visible depth planes
 *   - Embodied camera (standing height, slow push-in)
 *   - Temporal presence (haze drift, fabric movement)
 *   - Acoustic-visual coherence (velvet surface + brass surface visible)
 */

export type DirectorsPackage = {
  cinematiquePrompt: string;
  shotList: Array<{
    shotNumber: number;
    shotType: string;
    description: string;
    duration: string;
    cameraMovement: string;
    lightingNote: string;
  }>;
  productionNotes: {
    fabricPhysics: string;
    lightingSetup: string;
    cameraPsychology: string;
    atmosphericElements: string;
  };
  directorStatement: string;
  concert?: {
    title?: string;
    artistName?: string;
    venue?: string;
    moodPreset?: string;
    visualPreset?: string;
    cameraStyle?: string;
    lightingKelvin?: number;
    characters?: string;
  };
};

export type PromptBuildOptions = {
  directorsPackage: DirectorsPackage;
  /** Override the primary shot to use for the video prompt (default: shot 1) */
  primaryShotIndex?: number;
  /** Duration in seconds for the video (default: 10) */
  durationSeconds?: number;
};

/**
 * Visual preset → lighting layer overrides
 */
const VISUAL_PRESET_OVERRIDES: Record<string, {
  lightLayer: string;
  atmosphereLayer: string;
  contrastLayer: string;
}> = {
  shadow_and_smoke: {
    lightLayer: "single tungsten practical at 1800K, hard shadow edge at 45 degrees, motivated source only, footlight upwash, 70% of frame in deep shadow",
    atmosphereLayer: "oil-based haze stratifies at chest height, Mie forward scattering creates light column, cigarette micro-turbulence, haze density 0.5, smoke curl visible in beam",
    contrastLayer: "extreme chiaroscuro, warm amber dominant, cinematic realism, film grain texture, anamorphic lens flare",
  },
  golden_rim: {
    lightLayer: "2400K amber footlights, golden rim lighting separating performer from dark background, satin fabric catching warm glow at thirty degrees, theatrical stage lighting",
    atmosphereLayer: "warm bokeh in background, subtle haze stratified at waist height, haze density 0.3",
    contrastLayer: "warm amber color grading, rich shadow detail, intimate performance atmosphere, high contrast",
  },
  venetian_cage: {
    lightLayer: "venetian blind shadow bars casting geometric patterns across stage, 2200K warm tungsten, strong directional sidelight, shadow bars at 45 degrees across fabric",
    atmosphereLayer: "minimal haze, shadow geometry clean and precise, haze density 0.2",
    contrastLayer: "film noir aesthetic, deep contrast, architectural shadow play, cinematic realism",
  },
  match_flare: {
    lightLayer: "single match or lighter flame at 1600K, extreme chiaroscuro, intimate close-up framing, flame not illuminating face, match flame casting negligible illumination on features",
    atmosphereLayer: "breath-close proximity, minimal haze, smoke from extinguished match rising",
    contrastLayer: "extreme contrast, dangerous beauty, film grain, ultra-warm micro-light",
  },
  none: {
    lightLayer: "single tungsten practical at 2500K, motivated source only, hard shadow edges",
    atmosphereLayer: "oil-based haze stratifies at chest height, haze density 0.4",
    contrastLayer: "high contrast, warm amber, cinematic realism",
  },
};

/**
 * Mood preset → subject layer modifiers
 */
const MOOD_SUBJECT_MODIFIERS: Record<string, string> = {
  intimate_jazz: "performer in intimate close-up, social distance under 1.2 meters, gaze directed toward camera position",
  high_energy: "performer in dynamic mid-shot, body in motion, fabric lag visible behind movement",
  noir_smoke: "performer partially obscured by shadow, one eye illuminated and one eye in shadow, face intentionally asymmetric",
  custom: "performer at center stage, standing height camera, slow push-in implied",
};

/**
 * Character → wardrobe layer
 */
const CHARACTER_WARDROBE: Record<string, string> = {
  the_red_head_singer: "deep crimson bias-cut silk charmeuse gown, fabric lag 0.3 seconds behind movement, Fresnel edge highlight at grazing angle, Marschner R-path warm orange-red specular on red hair under tungsten",
  the_fedora_man: "dark charcoal wool gabardine suit, fedora brim at 45 degrees creating hard shadow across upper face, jaw and lips lit, eyes concealed — the psychological grammar of concealment",
  custom: "period-appropriate 1940s attire, fabric responding to stage lighting",
};

/**
 * Assemble the 10-layer Cinématique video prompt from a Director's Package.
 *
 * The Expert Council's cinematiquePrompt is used as the semantic core (it
 * already encodes the physics vocabulary). This function wraps it with the
 * structured 10-layer formula, presence threshold overrides, and
 * AI-default-resistance phrases from Chapter 6.4.
 */
export function buildCinématiqueVideoPrompt(options: PromptBuildOptions): string {
  const { directorsPackage, primaryShotIndex = 0 } = options;
  const pkg = directorsPackage;
  const concert = pkg.concert ?? {};

  // ── Layer 1: Environment ──────────────────────────────────────────────────
  const layer1 = "Subterranean 1940s noir jazz club interior, low ceiling 9 to 12 feet, 30 feet maximum depth, intimate space, velvet and brass surfaces dominate, dark mahogany bar visible in background";

  // ── Layer 2: Time / Era ───────────────────────────────────────────────────
  const layer2 = "late night post-midnight, 1940s era, timeless and sealed from the outside world";

  // ── Layer 3: Subject ──────────────────────────────────────────────────────
  const moodKey = concert.moodPreset ?? "intimate_jazz";
  const moodModifier = MOOD_SUBJECT_MODIFIERS[moodKey] ?? MOOD_SUBJECT_MODIFIERS.custom;

  // Determine primary character
  const characters = concert.characters ?? "";
  let wardrobeLayer = "";
  if (characters.toLowerCase().includes("red head") || characters.toLowerCase().includes("singer")) {
    wardrobeLayer = CHARACTER_WARDROBE.the_red_head_singer;
  } else if (characters.toLowerCase().includes("fedora")) {
    wardrobeLayer = CHARACTER_WARDROBE.the_fedora_man;
  } else {
    wardrobeLayer = CHARACTER_WARDROBE.custom;
  }
  const layer3 = `${moodModifier}, ${wardrobeLayer}`;

  // ── Layer 4: Light Source Geometry ───────────────────────────────────────
  const visualKey = concert.visualPreset ?? "shadow_and_smoke";
  const presetOverrides = VISUAL_PRESET_OVERRIDES[visualKey] ?? VISUAL_PRESET_OVERRIDES.none;
  const kelvin = concert.lightingKelvin ?? 2500;
  const layer4 = `${presetOverrides.lightLayer}, primary source at ${kelvin}K`;

  // ── Layer 5: Light Hierarchy ──────────────────────────────────────────────
  const layer5 = "70% of frame in deep shadow, spotlight dominant, performer is brightest object in frame, background dissolves into darkness, no fill light, no overhead wash";

  // ── Layer 6: Atmospheric Density ─────────────────────────────────────────
  const layer6 = presetOverrides.atmosphereLayer;

  // ── Layer 7: Foreground Depth Elements ───────────────────────────────────
  const layer7 = "foreground out-of-focus glassware catching warm specular highlight, four visible depth planes: foreground glass, mid-ground haze, performer, background darkness, acoustic-visual coherence: velvet drape visible, brass fixture in mid-ground";

  // ── Layer 8: Lens and Camera Position ────────────────────────────────────
  const cameraStyle = concert.cameraStyle ?? "intimate_close";
  let lensLayer: string;
  if (cameraStyle.includes("wide") || cameraStyle.includes("establishing")) {
    lensLayer = "35mm lens, camera at standing height 1.6 meters, slow push-in 0.5 centimeters per second, embodied camera movement implying a body in the room";
  } else if (cameraStyle.includes("extreme") || cameraStyle.includes("close")) {
    lensLayer = "85mm lens at f/1.4, camera at standing height 1.6 meters, slow push-in 1 centimeter per second, background dissolved into warm bokeh, breathing instability 0.2 Hz";
  } else {
    lensLayer = "85mm lens at f/1.4, camera at standing height 1.6 meters, slow push-in 0.5 to 2 centimeters per second, romantic compression, background dissolution, embodied camera";
  }
  const layer8 = lensLayer;

  // ── Layer 9: Texture and Material Cues ───────────────────────────────────
  const layer9 = "deep crimson velvet pile absorbs 85% of incident light — richness from absorption not reflection, aged brass metallic 0.95 roughness 0.45 warm gold reflection, dark mahogany bar matte absorption, glass reflection plane doubles spatial depth, stage elevation 6 to 18 inches visible";

  // ── Layer 10: Contrast and Color Palette ─────────────────────────────────
  const layer10 = presetOverrides.contrastLayer;

  // ── AI Default Resistance Phrases (Chapter 6.4) ──────────────────────────
  const aiOverrides = [
    "minimal fill",
    "asymmetrical lighting",
    "asymmetrical shadow",
    "no visible catchlights",
    "face intentionally underexposed in shadow zones",
    "hard shadow edges required",
    "soft shadows forbidden",
    "no overhead wash",
    "no fluorescent sources",
    "no cool-white sources",
  ].join(", ");

  // ── Presence Threshold Confirmations (Chapter 28 / 31) ───────────────────
  const presenceThresholds = [
    "shadow coverage minimum 70% of frame",
    "chiaroscuro ratio minimum 8:1",
    "four visible depth planes confirmed",
    "temporal presence: haze drift 0.2 to 0.4 meters per second",
    "fabric lag 0.3 seconds behind movement",
    "social presence: performer gaze toward camera position",
    "acoustic-visual coherence: velvet surface and brass surface both visible",
  ].join(", ");

  // ── Assemble the Full 10-Layer Prompt ────────────────────────────────────
  const tenLayerPrompt = [
    layer1,
    layer2,
    layer3,
    layer4,
    layer5,
    layer6,
    layer7,
    layer8,
    layer9,
    layer10,
    aiOverrides,
    presenceThresholds,
    "cinematic realism, photorealistic, 4K",
  ].join(", ");

  // ── Integrate Expert Council's Cinématique Prompt ────────────────────────
  // The Expert Council prompt is the semantic core; the 10-layer formula
  // wraps it with structural specificity and AI-override phrases.
  // We prepend the structured layers and append the Expert Council's language.
  const finalPrompt = `${tenLayerPrompt}. ${pkg.cinematiquePrompt}`;

  return finalPrompt;
}

/**
 * Extract the primary shot description from a Director's Package shot list.
 */
export function getPrimaryShot(
  directorsPackage: DirectorsPackage,
  shotIndex = 0
): DirectorsPackage["shotList"][number] | null {
  return directorsPackage.shotList?.[shotIndex] ?? null;
}
